baseurl = "http://obedmr.com/"
languageCode = "en-us"
defaultContentLanguage = "en-us"
title = "Obed's Blog"
theme = "hugo-tranquilpeak-theme"
disqusShortname = "obedmr-com"
googleAnalytics = "UA-51720562-1"
paginate = 7
canonifyurls = true

[permalinks]
  post = "/:year/:month/:slug/"

[taxonomies]
  tag = "tags"
  category = "categories"
  archive = "archives"

[author]
  name = "Obed N Munoz"
  bio = ""
  job = "Software Engineer"
  location = "Mexico"
  gravatarEmail = "obed.n.munoz@gmail.com"
  picture = "https://cdn1.iconfinder.com/data/icons/ninja-things-1/1772/ninja-simple-512.png"
  twitter = "_obedmr"
  # googlePlus = "+ThibaudLepretre"

# Menu Configuration
[[menu.main]]
  weight = 1
  identifier = "home"
  name = "Home"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-home\"></i>"
  url = "/"
[[menu.main]]
  weight = 2
  identifier = "music"
  name = "Music"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-music\"></i>"
  url = "/music"
[[menu.main]]
  weight = 3
  identifier = "talks"
  name = "Talks"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-microphone\"></i>"
  url = "/tags/talks"
[[menu.main]]
  weight = 4
  identifier = "bible"
  name = "Bible Studies"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-book\"></i>"
  url = "/tags/bible"
[[menu.main]]
  weight = 5
  identifier = "categories"
  name = "Categories"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-bookmark\"></i>"
  url = "/categories"
[[menu.main]]
  weight = 6
  identifier = "about"
  name = "About"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-question\"></i>"
  url = "/#about"

[[menu.links]]
  weight = 1
  identifier = "github"
  name = "GitHub"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-github\"></i>"
  url = "https://github.com/obedmr"
[[menu.links]]
  weight = 2
  identifier = "linkedin"
  name = "Linkedin"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-linkedin\"></i>"
  url = "https://www.linkedin.com/in/obedmr/"


[[menu.misc]]
  weight = 0
  identifier = "rss"
  name = "RSS"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-rss\"></i>"
  url = "/index.xml"

[params]
  clearReading = true

  hierarchicalCategories = true

  description = "Obed N Munoz Blog"

  sidebarBehavior = 2

   coverImage = "http://lanceweiler.com/wp-content/uploads/2016/12/mts.jpg"

   imageGallery = true

   thumbnailImage = true

  thumbnailImagePosition = "bottom"

  autoThumbnailImage = true

  [params.header.rightLink]
    class = ""
    icon = ""
    url = "/#about"
